### ISSUE TITLE
 [SAH-82]: Order Tracking Tab

### ISSUE THREAD

**Issue by Emmanuel-Melon** [Emmanuel-Melon/sahil#165]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when \[...\]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Emmanuel-Melon** [comment]
Wait, was this actually completed?

**Comment by Maiz27** [comment]
> Wait, was this actually completed?

No, there is a sync issue with Linear.
