### ISSUE TITLE
[SAH-19]: Configure Landing Page (Clean up)

### ISSUE THREAD

**Issue by Maiz27** [Emmanuel-Melon/sahil#28]
## Details

* public folder missing, create one
* src folder missing, create one
* move app into src folder
* update next config file of landing page to enable the app server to run from the src directory
* create components folder
* add images & favicon
* update layout file by adding page title and font
* switch Inter font to Montserrat

**Comment by Emmanuel-Melon** [comment]
Aren't we using https://github.com/Emmanuel-Melon/sahil/tree/main/apps/website?
